# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd68268668dcc39480c4607c0adae680864747ee69437c7144578f37f03c6d7225a3e18eef6f329682b46fa251a46973679c86d8e972034029fa0d71ed4e6223

test:
  secret_key_base: 3aa293cf0cef4742064012ec512d9bef4832fae6f57c0ed1b617e830fca0fcfd88193f6c796e9db511fef6a4fce70bb236ad6d8f4ba889de57d4980ab399fe63

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
